export type Color = 'red' | 'orange' | 'amber' | 'yellow' | 'lime' | 'green' | 'emerald' | 'teal' | 'cyan' | 'sky' | 'blue' | 'indigo' | 'violet' | 'purple' | 'fuchsia' | 'pink' | 'rose'

export type HexColor = `#${Uppercase<string>}`

export const colorMap: Record<Color, HexColor> = {
  red: '#DC2626',
  orange: '#F97316',
  amber: '#D97706',
  yellow: '#EAB308',
  lime: '#84CC16',
  green: '#22C55E',
  emerald: '#10B981',
  teal: '#14B8A6',
  cyan: '#06B6D4',
  sky: '#0EA5E9',
  blue: '#2563EB',
  indigo: '#4F46E5',
  violet: '#7C3AED',
  purple: '#A855F7',
  fuchsia: '#D946EF',
  pink: '#EC4899',
  rose: '#E11D48',
}
export const backdropColorMap: Record<Color, HexColor> = {
  red: '#DC26261A',
  orange: '#F973161A',
  amber: '#D977061A',
  yellow: '#EAB3081A',
  lime: '#84CC161A',
  green: '#22C55E1A',
  emerald: '#10B9811A',
  teal: '#14B8A61A',
  cyan: '#06B6D41A',
  sky: '#0EA5E91A',
  blue: '#2563EB1A',
  indigo: '#4F46E51A',
  violet: '#7C3AED1A',
  purple: '#A855F71A',
  fuchsia: '#D946EF1A',
  pink: '#EC48991A',
  rose: '#E11D481A',
}


export const colorLanguageMap: Record<string, Color> = {
  javascript: 'yellow',
  python: 'yellow',
  java: 'violet',
  typescript: 'blue',
  go: 'blue',
  graphql: 'rose',
  css: 'cyan',
  scss: 'rose',
  sass: 'rose',
  html: 'orange',
  markdown: 'orange',
  gql: 'rose',
  js: 'yellow',
  md: 'indigo',
  svelte: 'amber',
  ts: 'blue',
  rs: 'orange',
  rust: 'orange',
  tsx: 'blue',
  jsx: 'blue',
  json: 'green',
  powershell: 'cyan',
  astro: 'orange',
}

export const languageNameMap: Record<string, string> = {
  js: 'JavaScript',
  javascript: 'JavaScript',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  css: 'CSS',
  scss: 'SCSS',
  java: 'Java',
  html: 'HTML',
  svelte: 'Svelte',
  md: 'Markdown',
  json: 'JSON',
  py: 'Python',
  python: 'Python',
  jsx: 'JavaScript React',
  tsx: 'TypeScript React',
  rs: 'Rust',
  rust: 'Rust',
  graphql: 'GraphQL',
  gql: 'GraphQL',
  go: 'Go',
  vue: 'Vue',
  php: 'PHP',
  c: 'C',
  cpp: 'C++',
  cs: 'C#',
  sh: 'Shell',
  bash: 'Bash',
  rb: 'Ruby',
  powershell: 'PowerShell',
  astro: 'Astro',
}